services:
  - type: web
    name: lr7-bot-corwindev
    env: node
    region: oregon
    plan: free
    buildCommand: cd vendor/CorwinDev-Discord-Bot && npm install
    startCommand: cd vendor/CorwinDev-Discord-Bot && npm start
    envVars:
      - key: PORT
        value: "10000"
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: LAVALINK_HOST
        sync: false
      - key: LAVALINK_PORT
        value: "80"
      - key: LAVALINK_PASSWORD
        value: CorwinDev
      - key: LAVALINK_SECURE
        value: "false"
  - type: web
    name: lr7-api
    env: node
    region: oregon
    plan: free
    buildCommand: cd vendor/VantyxBot/api && npm install
    startCommand: cd vendor/VantyxBot/api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "10000"
      - key: DASHBOARD_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
  - type: web
    name: lr7-dashboard
    env: node
    region: oregon
    plan: free
    buildCommand: cd vendor/VantyxBot/dashboard && npm install && npm run build
    startCommand: cd vendor/VantyxBot/dashboard && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DASHBOARD_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_API_PORT
        value: "443"
      - key: NEXT_PUBLIC_PROJECT_VERSION
        value: "1.0"
      - key: DASHBOARD_URL
        sync: false
      - key: API_URL
        sync: false
      - key: API_PORT
        value: "443"
