services:
  - type: worker
    name: lr7-bot-unified
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node vendor/VantyxBot/bot/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: MAIN_GUILD_ID
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DASHBOARD_URL
        sync: false
      - key: API_URL
        sync: false
      - key: API_PORT
        value: "443"
      - key: OWNER_IDS
        sync: false
      - key: MAIN_GUILD_ID
        sync: false
  - type: web
    name: lr7-api
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node vendor/VantyxBot/api/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: "10000"
      - key: DASHBOARD_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
  - type: web
    name: lr7-dashboard
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && cd vendor/VantyxBot/dashboard && npm run build
    startCommand: cd vendor/VantyxBot/dashboard && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_DASHBOARD_URL
        sync: false
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_API_PORT
        value: "443"
      - key: NEXT_PUBLIC_PROJECT_VERSION
        value: "1.0"
      - key: DASHBOARD_URL
        sync: false
      - key: API_URL
        sync: false
      - key: API_PORT
        value: "443"
